sudo: false
language: node_js
branches:
  only:
    - master
cache:
  npm: true
  directories:
    - .cache
env:
  global:
    - AWS_BUCKET=nlsmith.com
    - AWS_REGION=us-east-2
    - AWS_ACCESS_KEY_ID=AKIAZ3Z5DNF7YH2MITCV
    # AWS_SECRET_ACCESS_KEY
    - secure: "FRsDCnsdK4qJhYhX+qZZCp7b69QmPHy9iy6dWHgQpVSJS+mpveDXL+X3lLAAuLHUrlrJUvnPstBPuM9yrPVKdqY8wQCna5lbPy3EJvLz0XT+4o84IDvnPAotfBWWZkV2rEIhIbIjDjeIkz/fSJKbr/ExVbnzzNxejhRBQC2+dxg="
    # CLOUDFLARE_API_KEY
    - secure: "cKft3OkcO+jjy9ckmu6kjJ45fiqiNlGPXay2jCsOCTQ7Jdq/8264VP4lkuHVUxhzHN7Mdy2gOhv4lce8R/cEjl8P8gr+oTTfbp7xW11BqBUXu5H8/Mh4B1tOZnAQnyylhWYicMQqLNsbGAHdllvH6D75VaemvQ+7YgYZkLN+Ed0="
    # CLOUDFLARE_EMAIL
    - secure: "YNmhyfaJyYykct2oPR2nxK7VkCXtttmml1KUfIHv2o6Yb3gtH3hdUUD+QjOSoRzZ11JBD+vcA0iEOHPF2MM/AyLwaVw7rCMUlOkB4pR6RtfdlFEvQefIhTYXK3ORMKt+Gugr2Yhw/yXu02pAvwRsUmeceUW3dCVn0n7yVsV7pC4="
    # CLOUDFLARE_ZONE_ID
    - secure: "IMVyio2oLSJjIXF6vmOEFLitwdF8ZJd6g0kB0LC5Hwo8nkYw2LHvcL8uOattacL6XSfhOcN2kfmh7+ExJLmjKNbR8iT/gmaBrPOsfKr+ENav7TspGb45++j3wUSIpIdVPjAzaE4rbowr5ocjIlB9+IoMS9YmskVBNOZ2dbQBWr0="
script: npm run build && npm run deploy && bin/purge-cloudflare-cache.sh
