sudo: false
language: ruby
rvm: 2.3.2
branches:
  only:
  - master
cache:
  bundler: true
  directories:
  - build
env:
  global:
  - AWS_BUCKET=nlsmith.com
  - AWS_DEFAULT_REGION=us-east-2
  - AWS_ACCESS_KEY_ID=AKIAIFFUZ3LH37VBLV6A
  # AWS_SECRET_ACCESS_KEY
  - secure: "GhEE6B6j9jQ9bf0c7ixBlKh3mNQ1l70T3Fwb/VsdfIOSY2kmaB4iBDA9NlljzVb+EWBfXjf9zgxBZaLMmrsnOnPBGvm5oz5SRQE32dBavwGfKG2IxcUbgrL7XGjH2pGIe0BoO3CzY9Qb6Z1S6/mZ0INkmmjdd93UD64YmEr7Xuo="
script: bin/middleman build
